# Dataset root directory relative to the yolov5 directory
path: debug

# Train/val/test sets: specify directories, *.txt files, or lists
train: images/train
val: images/val
#test: images/test 

kpt_shape: [13, 3] # 13 body keypoints (face excluded, Neck included), dims: x, y, visible
flip_idx: [1, 0, 3, 2, 5, 4, 7, 6, 9, 8, 11, 10, 12] # left↔right mirror for augmentation

# Classes (example using 80 COCO classes)
names:
    0: person
